config/routes.rb
Rails.application.routes.draw do
  # Get /about
  get "/about-us", to: "about#index", as: :about # rename the name as about (about url is about-us)
  
  get "sign_up", to: "registrations#new" 
  post "sign_up", to: "registrations#create"
  delete "logout", to: "sessions#destroy"

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual


class User < ApplicationRecord
  has_secure_password # function to hash password

  # validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ , message:  "Must be a valid email address"} # email as required field
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP , message:  "Must be a valid email address"} # email as required field
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find_by(id: session[:user_id]) # if user in session, add the user object
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@user = User.new # @ -> instance variable -> visible in view
	end
	def create
		# params ==> Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"test@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign Up"}
		# render plain: params[:user] # return {"email"=>"test@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign Up"}
		@user = User.new(user_params) # create new user
		if @user.save #save to db
      session[:user_id] = @user.id # add userID in session
			redirect_to root_path, notice: "Successfully created account!!" #redirect to home page
		else
			render :new
		end
	end

	private
	
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1 id="about_us">About the project hhahah</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buffer Clone by</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial: "shared/flash"%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-item-center justify-content-center">
  <h1 id="">Welcome To the Home page of Buffer clone</h1>

  <% if @user%>
    Logged in as <%= @user.email%>
    <%= button_to "Logout", logout_path, method: :delete %>
  <% end%> 
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info mt-4" role="alert">
		<%= flash[:notice] %>
	</div>
<% end%>

<% if flash[:alert]%>
	<div class="alert alert-danger mt-4" role="alert">
		<%= flash[:alert] %>
	</div>
<% end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Buffer", root_path, class: "navbar-brand"%>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>